# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: msa-redis
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    app: msa-redis
--- 
# Redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: msa-redis
  template:
    metadata:
      labels:
        app: msa-redis
    spec:
      containers:
      - name: msa-redis
        image: suhyen/msa-redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-pvc
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
