apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-front
  template:
    metadata:
      labels:
        app: msa-front
    spec:
      containers:
        - name: msa-front
          image: suhyen/msa-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: msa-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
