### hisujung url ###
# member: http://hisujung/member 
# notice: http://hisujung/notice
# portfolio: http://hisujung/portfolio



apiVersion: extensions/v1
kind: Ingress
metadata:
  name: hisujung-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hisujung
    http:
      paths:
      - path: /member
        pathType: Prefix
        backend:
          service:
          name: member-service
          port: 
            number: 80
      - path: /notice
        pathType: Prefix
        backend:
          service:
          name: notice-service
          port: 
            number: 8080
      - path: /portfolio
        pathType: Prefix
        backend:
          service:
          name: portfolio-service
          port: 
            number: 3001
      - path: /springcloudgateway
        pathType: Prefix
        backend:
          service:
          name: spring-cloud-gateway-svc
          port: 
            number: 80

