apiVersion: apps/v1
kind: Deployment
metadata: 
  name: member-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: msa-member
  template:
    metadata:
      labels:
        app: msa-member
    spec: 
      containers:
      - name: msa-member
        image: jekim12/msa-member:latest
        ports:
        - containerPort: 8080
        env: 
        - name: MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: mysql-url
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: mysql-username      
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: mysql-password
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: redis-port
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: email-username
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: email-password 
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec: 
  selector:
    app: msa-member
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
