apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: k8s-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-redis
  template:
    metadata:
      labels:
        app: k8s-redis
    spec:
      containers:
      - name: k8s-redis
        image: redis:7.2.4-alpine3.19
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: k8s-redis
spec:
  selector:
    app: k8s-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
