apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: bitnami/redis:6.2.6
          env:
            - name: REDIS_REPLICATION_MODE
              value: "master"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-1
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      instance: slave-1
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
        instance: slave-1
    spec:
      containers:
        - name: redis-slave-1
          image: bitnami/redis:6.2.6
          env:
            - name: REDIS_REPLICATION_MODE
              value: "slave"
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-1
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: slave
    instance: slave-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-2
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      instance: slave-2
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
        instance: slave-2
    spec:
      containers:
        - name: redis-slave-2
          image: bitnami/redis:6.2.6
          env:
            - name: REDIS_REPLICATION_MODE
              value: "slave"
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-2
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: slave
    instance: slave-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-1
spec:
  selector:
    matchLabels:
      app: redis
      role: sentinel
      instance: sentinel-1
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
        instance: sentinel-1
    spec:
      containers:
        - name: redis-sentinel-1
          image: bitnami/redis-sentinel:6.2.6
          env:
            - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
              value: "3000"
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_MASTER_SET
              value: "master-name"
            - name: REDIS_SENTINEL_QUORUM
              value: "2"
          ports:
            - containerPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-1
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: redis
    role: sentinel
    instance: sentinel-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-2
spec:
  selector:
    matchLabels:
      app: redis
      role: sentinel
      instance: sentinel-2
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
        instance: sentinel-2
    spec:
      containers:
        - name: redis-sentinel-2
          image: bitnami/redis-sentinel:6.2.6
          env:
            - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
              value: "3000"
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_MASTER_SET
              value: "master-name"
            - name: REDIS_SENTINEL_QUORUM
              value: "2"
          ports:
            - containerPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-2
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: redis
    role: sentinel
    instance: sentinel-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel-3
spec:
  selector:
    matchLabels:
      app: redis
      role: sentinel
      instance: sentinel-3
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
        instance: sentinel-3
    spec:
      containers:
        - name: redis-sentinel-3
          image: bitnami/redis-sentinel:6.2.6
          env:
            - name: REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS
              value: "3000"
            - name: REDIS_MASTER_HOST
              value: "redis-master"
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_MASTER_SET
              value: "master-name"
            - name: REDIS_SENTINEL_QUORUM
              value: "2"
          ports:
            - containerPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-3
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: redis
    role: sentinel
    instance: sentinel-3
