apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-rabbitmq-pvc
  labels:
    app: k8s-rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-rabbitmq
  labels:
    app: k8s-rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: k8s-rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-rabbitmq
spec:
  replicas: 1
  serviceName: k8s-rabbitmq
  selector:
    matchLabels:
      app: k8s-rabbitmq
  template:
    metadata:
      labels:
        app: k8s-rabbitmq
    spec:
      containers:
      - name: k8s-rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate
