apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-portfolio
spec:
  replicas: 1
  selector: # 디플로이먼트 제어하의 레플리카셋과 파드를 대응시키기 위해 라벨 사용
    matchLabels:
      app: msa-portfolio
  template: # 파드 템플릿
    metadata:
      labels:
        app: msa-portfolio
    spec:
      containers: # 파드 컨테이너의 사양
      - name: msa-portfolio
        image: julia2039/msa-portfolio:latest
        ports:
          - containerPort: 8080
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: url
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
---

apiVersion: v1
kind: Service
metadata:
  name: msa-portfolio
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 8080
  selector:
    app: msa-portfolio




