apiVersion: apps/v1
kind: Deployment
metadata: 
  name: msa-recommend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-recommend
  template:
    metadata:
      labels:
        app: msa-recommend
    spec:
      containers:
      - name: msa-recommend
        image: hyezis/msa-recommend:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: msa-recommend
spec:
  type: ClusterIP
  selector:
    app: msa-recommend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      
